package Autos;

import Clases.clsAutos;
import Seguridad.clsGestor;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author oscar
 */
public class FrmActualizar extends javax.swing.JInternalFrame {

    private Object btnActualizar;
    private clsGestor myGestor;
    private int idAuto;

    /**
     * Creates new form FrmActualizar
     */
    public FrmActualizar() {
        initComponents();
        this.myGestor = new clsGestor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jActualizarCarro = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JButton();
        btnLimpiarBuscador = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        lbBuscar = new javax.swing.JLabel();
        lbInformacionFiltrar = new javax.swing.JLabel();
        lbCantidadRequerida2 = new javax.swing.JLabel();
        lbCantidadRequerida5 = new javax.swing.JLabel();
        lbCantidad4 = new javax.swing.JLabel();
        txtPasajeros = new javax.swing.JFormattedTextField();
        lbCantidad2 = new javax.swing.JLabel();
        lbCantidad = new javax.swing.JLabel();
        txtChasis = new javax.swing.JFormattedTextField();
        lbCódigoRequerido2 = new javax.swing.JLabel();
        lbCantidadRequerida8 = new javax.swing.JLabel();
        lbCantidadRequerida6 = new javax.swing.JLabel();
        lbTipoRequerido = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lbCantidad3 = new javax.swing.JLabel();
        lbCilindrada = new javax.swing.JLabel();
        lbCantidad6 = new javax.swing.JLabel();
        txtMotor = new javax.swing.JTextField();
        lbMarca1 = new javax.swing.JLabel();
        lbCantidadRequerida3 = new javax.swing.JLabel();
        txtCilidrada = new javax.swing.JFormattedTextField();
        txtModelo = new javax.swing.JTextField();
        lbMarca = new javax.swing.JLabel();
        comboxTipoEstilo = new javax.swing.JComboBox<>();
        lbTipo = new javax.swing.JLabel();
        lbCantidad1 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtKilometraje = new javax.swing.JFormattedTextField();
        txtEstado = new javax.swing.JFormattedTextField();
        lbMotor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAnotaciones = new javax.swing.JTextArea();
        lbCantidadRequerida = new javax.swing.JLabel();
        btActualizar = new javax.swing.JButton();
        lbCombustible = new javax.swing.JLabel();
        txtCombustible = new javax.swing.JFormattedTextField();
        lbCantidadRequerida7 = new javax.swing.JLabel();
        lbCantidadRequerida1 = new javax.swing.JLabel();
        lbCódigoRequerido = new javax.swing.JLabel();
        txtTransmision = new javax.swing.JFormattedTextField();
        lbCódigoRequerido3 = new javax.swing.JLabel();
        txtAno = new javax.swing.JFormattedTextField();
        lbCódigo = new javax.swing.JLabel();
        txtValor = new javax.swing.JFormattedTextField();
        lbCantidadRequerida4 = new javax.swing.JLabel();
        lbDescripción = new javax.swing.JLabel();
        lbCantidadRequerida9 = new javax.swing.JLabel();
        lbCódigoRequerido1 = new javax.swing.JLabel();
        btLimpiar = new javax.swing.JButton();
        lbCantidad5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Actualizar informacion de autos");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/icons8-car-16.png"))); // NOI18N

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/icons8-search-16.png"))); // NOI18N
        btnBuscar.setText("Buscar");

        btnLimpiarBuscador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/clean-16.png"))); // NOI18N
        btnLimpiarBuscador.setText("Limpiar");
        btnLimpiarBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarBuscadorActionPerformed(evt);
            }
        });

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });

        lbBuscar.setText("Buscar:");

        lbInformacionFiltrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbInformacionFiltrar.setText("Ingrese el código del Auto.");

        lbCantidadRequerida2.setForeground(new java.awt.Color(153, 0, 0));
        lbCantidadRequerida2.setText("*");

        lbCantidadRequerida5.setForeground(new java.awt.Color(153, 0, 0));
        lbCantidadRequerida5.setText("*");

        lbCantidad4.setText("Kilometraje:");

        txtPasajeros.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        lbCantidad2.setText("Chasis:");

        lbCantidad.setText("Año:");

        txtChasis.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        lbCódigoRequerido2.setForeground(new java.awt.Color(153, 0, 0));
        lbCódigoRequerido2.setText("*");

        lbCantidadRequerida8.setForeground(new java.awt.Color(153, 0, 0));
        lbCantidadRequerida8.setText("*");

        lbCantidadRequerida6.setForeground(new java.awt.Color(153, 0, 0));
        lbCantidadRequerida6.setText("*");

        lbTipoRequerido.setForeground(new java.awt.Color(153, 0, 0));
        lbTipoRequerido.setText("*");

        txtCodigo.setEditable(false);

        lbCantidad3.setText("Transmision:");

        lbCilindrada.setText("Cilindrada:");

        lbCantidad6.setText("Valor:");

        lbMarca1.setText("Modelo:");

        lbCantidadRequerida3.setForeground(new java.awt.Color(153, 0, 0));
        lbCantidadRequerida3.setText("*");

        txtCilidrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        lbMarca.setText("Marca:");

        comboxTipoEstilo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo", "4x4", "4x2", "Compactos", "Crossover", "Coupé", "Deportivos", "Crossover", "Convertibles", "Hatchback", "MPV", "Pick-up", "Sedán", "Station Wagon", "SUV", "Utilitarios", " ", " " }));

        lbTipo.setText("Estilo de Auto:");

        lbCantidad1.setText("Pasajeros:");

        txtKilometraje.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        txtEstado.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        lbMotor.setText("Motor:");

        txtAnotaciones.setColumns(20);
        txtAnotaciones.setRows(5);
        jScrollPane1.setViewportView(txtAnotaciones);

        lbCantidadRequerida.setForeground(new java.awt.Color(153, 0, 0));
        lbCantidadRequerida.setText("*");

        btActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/save-16.png"))); // NOI18N
        btActualizar.setText("Actualizar");
        btActualizar.setEnabled(false);
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });

        lbCombustible.setText("Combustible:");

        txtCombustible.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        lbCantidadRequerida7.setForeground(new java.awt.Color(153, 0, 0));
        lbCantidadRequerida7.setText("*");

        lbCantidadRequerida1.setForeground(new java.awt.Color(153, 0, 0));
        lbCantidadRequerida1.setText("*");

        lbCódigoRequerido.setForeground(new java.awt.Color(153, 0, 0));
        lbCódigoRequerido.setText("*");

        txtTransmision.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        lbCódigoRequerido3.setForeground(new java.awt.Color(153, 0, 0));
        lbCódigoRequerido3.setText("*");

        txtAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        lbCódigo.setText("Código:");

        txtValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        lbCantidadRequerida4.setForeground(new java.awt.Color(153, 0, 0));
        lbCantidadRequerida4.setText("*");

        lbDescripción.setText("Anotaciones del Vehiculo.");

        lbCantidadRequerida9.setForeground(new java.awt.Color(153, 0, 0));
        lbCantidadRequerida9.setText("*");

        lbCódigoRequerido1.setForeground(new java.awt.Color(153, 0, 0));
        lbCódigoRequerido1.setText("*");

        btLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/clean-16.png"))); // NOI18N
        btLimpiar.setText("Limpiar");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        lbCantidad5.setText("Estado:");

        javax.swing.GroupLayout jActualizarCarroLayout = new javax.swing.GroupLayout(jActualizarCarro);
        jActualizarCarro.setLayout(jActualizarCarroLayout);
        jActualizarCarroLayout.setHorizontalGroup(
            jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jActualizarCarroLayout.createSequentialGroup()
                .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jActualizarCarroLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jActualizarCarroLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jActualizarCarroLayout.createSequentialGroup()
                                .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jActualizarCarroLayout.createSequentialGroup()
                                        .addGap(309, 309, 309)
                                        .addComponent(btnBuscar)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLimpiarBuscador))
                                    .addGroup(jActualizarCarroLayout.createSequentialGroup()
                                        .addGap(201, 201, 201)
                                        .addComponent(lbBuscar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jActualizarCarroLayout.createSequentialGroup()
                                        .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jActualizarCarroLayout.createSequentialGroup()
                                                .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jActualizarCarroLayout.createSequentialGroup()
                                                        .addComponent(lbCantidad3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lbCantidadRequerida5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jActualizarCarroLayout.createSequentialGroup()
                                                        .addComponent(lbCantidad6)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lbCantidadRequerida8, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jActualizarCarroLayout.createSequentialGroup()
                                                        .addComponent(lbCantidad1)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lbCantidadRequerida3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtValor)
                                                    .addComponent(txtTransmision)
                                                    .addComponent(txtPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jActualizarCarroLayout.createSequentialGroup()
                                                    .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jActualizarCarroLayout.createSequentialGroup()
                                                            .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(lbMarca1)
                                                                .addComponent(lbCantidad))
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(lbCantidadRequerida, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(lbCódigoRequerido2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(jActualizarCarroLayout.createSequentialGroup()
                                                            .addComponent(lbMarca)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(lbCódigoRequerido1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jActualizarCarroLayout.createSequentialGroup()
                                                            .addComponent(lbCódigo)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(lbCódigoRequerido, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGap(26, 26, 26)
                                                    .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addComponent(txtModelo, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtMarca, javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jActualizarCarroLayout.createSequentialGroup()
                                                    .addComponent(lbDescripción)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(lbCantidadRequerida9, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jActualizarCarroLayout.createSequentialGroup()
                                                .addComponent(lbTipo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbTipoRequerido)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(comboxTipoEstilo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(jActualizarCarroLayout.createSequentialGroup()
                                                .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jActualizarCarroLayout.createSequentialGroup()
                                                        .addComponent(lbCilindrada)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(lbCantidadRequerida1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jActualizarCarroLayout.createSequentialGroup()
                                                        .addComponent(lbMotor)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lbCódigoRequerido3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jActualizarCarroLayout.createSequentialGroup()
                                                        .addComponent(lbCombustible)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lbCantidadRequerida2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jActualizarCarroLayout.createSequentialGroup()
                                                        .addComponent(lbCantidad2)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lbCantidadRequerida4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtChasis)
                                                    .addComponent(txtMotor)
                                                    .addComponent(txtCilidrada)
                                                    .addComponent(txtCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jActualizarCarroLayout.createSequentialGroup()
                                                .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jActualizarCarroLayout.createSequentialGroup()
                                                        .addComponent(lbCantidad4)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lbCantidadRequerida6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                                    .addGroup(jActualizarCarroLayout.createSequentialGroup()
                                                        .addComponent(lbCantidad5)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lbCantidadRequerida7, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(37, 37, 37)))
                                                .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtEstado)
                                                    .addComponent(txtKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(jActualizarCarroLayout.createSequentialGroup()
                                        .addGap(312, 312, 312)
                                        .addComponent(lbInformacionFiltrar)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jActualizarCarroLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btActualizar)
                                .addGap(18, 18, 18)
                                .addComponent(btLimpiar)))))
                .addContainerGap())
        );
        jActualizarCarroLayout.setVerticalGroup(
            jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jActualizarCarroLayout.createSequentialGroup()
                .addComponent(lbInformacionFiltrar)
                .addGap(12, 12, 12)
                .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiarBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jActualizarCarroLayout.createSequentialGroup()
                        .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jActualizarCarroLayout.createSequentialGroup()
                                .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbCódigo)
                                        .addComponent(lbCódigoRequerido)
                                        .addComponent(lbTipo))
                                    .addComponent(lbTipoRequerido))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(comboxTipoEstilo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMarca)
                            .addComponent(lbCódigoRequerido1)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbMotor)
                            .addComponent(lbCódigoRequerido3)))
                    .addGroup(jActualizarCarroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMarca1)
                    .addComponent(lbCódigoRequerido2)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCilindrada)
                    .addComponent(lbCantidadRequerida1)
                    .addComponent(txtCilidrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCantidad)
                    .addComponent(lbCantidadRequerida)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCombustible)
                    .addComponent(lbCantidadRequerida2)
                    .addComponent(txtCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCantidad1)
                    .addComponent(lbCantidadRequerida3)
                    .addComponent(txtPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCantidad2)
                    .addComponent(lbCantidadRequerida4)
                    .addComponent(txtChasis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCantidad3)
                    .addComponent(lbCantidadRequerida5)
                    .addComponent(txtTransmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCantidad4)
                    .addComponent(lbCantidadRequerida6)
                    .addComponent(txtKilometraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCantidad5)
                    .addComponent(lbCantidadRequerida7)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCantidad6)
                    .addComponent(lbCantidadRequerida8)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDescripción)
                    .addComponent(lbCantidadRequerida9))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jActualizarCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpiar)
                    .addComponent(btActualizar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jActualizarCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jActualizarCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarBuscadorActionPerformed
        this.txtBuscar.setText("");
        this.txtBuscar.requestFocus();
    }//GEN-LAST:event_btnLimpiarBuscadorActionPerformed
    private void LimpiarFormulario() {
        this.txtCodigo.setText("");
        this.txtMarca.setText("");
        this.txtModelo.setText("");
        this.txtAno.setText("");
        this.txtPasajeros.setText("");
        this.txtTransmision.setText("");
        this.txtValor.setText("");
        this.txtMotor.setText("");
        this.txtCilidrada.setText("");
        this.txtCombustible.setText("");
        this.txtChasis.setText("");
        this.txtKilometraje.setText("");
        this.txtEstado.setText("");
        this.comboxTipoEstilo.setSelectedIndex(0);
        this.txtAnotaciones.setText("");
    }
    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.Buscar();
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
        if (this.txtCodigo.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "El código es requerido.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.txtCodigo.requestFocus();
            return;
        }
        if (this.comboxTipoEstilo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione el estilo del auto.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.comboxTipoEstilo.requestFocus();
            return;
        }
        if (this.txtMarca.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "El nombre es requerido.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.txtMarca.requestFocus();
            return;
        }
        if (this.txtMotor.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "La cantidad es requerida.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.txtMotor.requestFocus();
            return;
        }
        if (this.txtModelo.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Introduzca el modelo del vehiculo.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.txtModelo.requestFocus();
            return;
        }
        if (this.txtCilidrada.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Introduzca la cilidrada del vehiculo.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.txtCilidrada.requestFocus();
            return;
        }
        if (this.txtAno.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Introduzca el año del vehiculo.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.txtAno.requestFocus();
            return;
        }
        if (this.txtCombustible.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Introduzca el tipo de combustibles.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.txtCombustible.requestFocus();
            return;
        }
        if (this.txtPasajeros.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Introduzca el numero de pasajeros.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.txtPasajeros.requestFocus();
            return;
        }
        if (this.txtChasis.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Introduzca el numero de chasis.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.txtChasis.requestFocus();
            return;
        }
        if (this.txtTransmision.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Introduzca el tipo de transmision.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.txtTransmision.requestFocus();
            return;
        }
        if (this.txtKilometraje.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Introduzca el kilometraje del vehiculo.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.txtKilometraje.requestFocus();
            return;
        }
        if (this.txtValor.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Introduzca el valor del vehiculo.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.txtValor.requestFocus();
            return;
        }
        if (this.txtEstado.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Introduzca el estado del vehiculo.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.txtEstado.requestFocus();
            return;
        }
        if (this.txtAnotaciones.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Introduzca la anotaciones del vehiculo.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.txtAnotaciones.requestFocus();
            return;
        }

        this.myGestor = new clsGestor();

    clsAutos myAutos = new clsAutos(
                this.idAuto,
                this.txtCodigo.getText().trim(),
                this.txtMarca.getText().trim(),
                this.txtModelo.getText().trim(),
                Integer.parseInt(this.txtAno.getText().trim()),
                this.comboxTipoEstilo.getSelectedItem().toString(),
                this.txtMotor.getText().trim(),
                this.txtCilidrada.getText().trim(),
                this.txtCombustible.getText().trim(),
                Integer.parseInt(this.txtPasajeros.getValue().toString()),
                this.txtChasis.getText().trim(),
                this.txtTransmision.getText().trim(),
                this.txtKilometraje.getText().trim(),
                this.txtEstado.getText().trim(),
                Integer.parseInt(this.txtValor.getValue().toString()),
                this.txtAnotaciones.getText().trim()            
            );

        boolean operacion = myGestor.ActualizarAutos(myAutos);

        if (operacion) {
            JOptionPane.showMessageDialog(this, "Se guardo la información correctamente.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.LimpiarFormulario();
            this.txtCodigo.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "No se logro guardar la información correctamente, Intentar nuevamente.", "Aviso", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btActualizarActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        this.LimpiarFormulario();
    }//GEN-LAST:event_btLimpiarActionPerformed
    private void Buscar() {
        String codigo = this.txtBuscar.getText().trim().toLowerCase();

        if (!codigo.isBlank() && !codigo.isEmpty()) {
            clsAutos myAuto = this.myGestor.ConsultarAutos(Integer.parseInt(this.txtBuscar.getText()));

            if (myAuto != null && myAuto.getIdAutos() > 0) {
                this.idAuto = myAuto.getIdAutos();
               this.txtCodigo.setText(myAuto.getCodigo());
                this.txtMarca.setText(myAuto.getMarca());
                this.txtModelo.setText(myAuto.getModelo());
                this.txtAno.setValue(myAuto.getAno()); 
                this.txtPasajeros.setValue(myAuto.getPasajeros());
                this.txtTransmision.setText(myAuto.getTransmision());
                this.txtValor.setValue(myAuto.getValor());
                this.txtMotor.setText(myAuto.getMotor());
                this.txtCilidrada.setText(myAuto.getCilindrada());
                this.txtCombustible.setText(myAuto.getCombustible());
                this.txtChasis.setText(myAuto.getChasis());
                this.txtKilometraje.setText(myAuto.getKilometraje());
                this.comboxTipoEstilo.setSelectedItem(myAuto.getEstilo());
                this.txtEstado.setText(myAuto.getEstado());
                this.txtAnotaciones.setText(myAuto.getAnotaciones());
                this.btActualizar.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "NO se ha encontrado el Vehiculo.", "Aviso", JOptionPane.WARNING_MESSAGE);
                this.btActualizar.setEnabled(false);
                this.txtBuscar.setText("");
            }

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiarBuscador;
    private javax.swing.JComboBox<String> comboxTipoEstilo;
    private javax.swing.JPanel jActualizarCarro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBuscar;
    private javax.swing.JLabel lbCantidad;
    private javax.swing.JLabel lbCantidad1;
    private javax.swing.JLabel lbCantidad2;
    private javax.swing.JLabel lbCantidad3;
    private javax.swing.JLabel lbCantidad4;
    private javax.swing.JLabel lbCantidad5;
    private javax.swing.JLabel lbCantidad6;
    private javax.swing.JLabel lbCantidadRequerida;
    private javax.swing.JLabel lbCantidadRequerida1;
    private javax.swing.JLabel lbCantidadRequerida2;
    private javax.swing.JLabel lbCantidadRequerida3;
    private javax.swing.JLabel lbCantidadRequerida4;
    private javax.swing.JLabel lbCantidadRequerida5;
    private javax.swing.JLabel lbCantidadRequerida6;
    private javax.swing.JLabel lbCantidadRequerida7;
    private javax.swing.JLabel lbCantidadRequerida8;
    private javax.swing.JLabel lbCantidadRequerida9;
    private javax.swing.JLabel lbCilindrada;
    private javax.swing.JLabel lbCombustible;
    private javax.swing.JLabel lbCódigo;
    private javax.swing.JLabel lbCódigoRequerido;
    private javax.swing.JLabel lbCódigoRequerido1;
    private javax.swing.JLabel lbCódigoRequerido2;
    private javax.swing.JLabel lbCódigoRequerido3;
    private javax.swing.JLabel lbDescripción;
    private javax.swing.JLabel lbInformacionFiltrar;
    private javax.swing.JLabel lbMarca;
    private javax.swing.JLabel lbMarca1;
    private javax.swing.JLabel lbMotor;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lbTipoRequerido;
    private javax.swing.JFormattedTextField txtAno;
    private javax.swing.JTextArea txtAnotaciones;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JFormattedTextField txtChasis;
    private javax.swing.JFormattedTextField txtCilidrada;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtCombustible;
    private javax.swing.JFormattedTextField txtEstado;
    private javax.swing.JFormattedTextField txtKilometraje;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtMotor;
    private javax.swing.JFormattedTextField txtPasajeros;
    private javax.swing.JFormattedTextField txtTransmision;
    private javax.swing.JFormattedTextField txtValor;
    // End of variables declaration//GEN-END:variables

}
