package Herramientas;

import Clases.clsActivo;
import Interfaces.intzGestor;
import Seguridad.clsGestor;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Oscar Zumbado Porras
 */
public class FrmActualizar extends javax.swing.JInternalFrame {

    private clsGestor myGestor;
    private int idActivo;

    /**
     * Creates new form FrmActualizar
     */
    public FrmActualizar() {
        initComponents();
        this.myGestor = new clsGestor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbInformacionFiltrar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnLimpiarBuscador = new javax.swing.JButton();
        lbBuscar = new javax.swing.JLabel();
        panelRegistroActivo = new javax.swing.JPanel();
        lbinfo = new javax.swing.JLabel();
        separadorEncabezado = new javax.swing.JSeparator();
        lbCódigo = new javax.swing.JLabel();
        lbCódigoRequerido = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lbNombre = new javax.swing.JLabel();
        lbNombreRequerido = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lbCantidad = new javax.swing.JLabel();
        lbCantidadRequerida = new javax.swing.JLabel();
        lbTipo = new javax.swing.JLabel();
        lbTipoRequerido = new javax.swing.JLabel();
        comboxTipo = new javax.swing.JComboBox<>();
        txtCantidad = new javax.swing.JFormattedTextField();
        lbEstado = new javax.swing.JLabel();
        lbEstadoRequerido = new javax.swing.JLabel();
        chkActivo = new javax.swing.JCheckBox();
        chkInactivo = new javax.swing.JCheckBox();
        lbFragilidad = new javax.swing.JLabel();
        lbFragilidadRequerido = new javax.swing.JLabel();
        comboxFragilidad = new javax.swing.JComboBox<>();
        lbDescripción = new javax.swing.JLabel();
        lbDescripcionRequerida = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaDescripcion = new javax.swing.JTextArea();
        btLimpiar = new javax.swing.JButton();
        btActualizar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Actualizar herramienta");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/icons8-update-16.png"))); // NOI18N

        lbInformacionFiltrar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbInformacionFiltrar.setText("Ingrese el código de la herramienta.");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarKeyPressed(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/icons8-search-16.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiarBuscador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/clean-16.png"))); // NOI18N
        btnLimpiarBuscador.setText("Limpiar");
        btnLimpiarBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarBuscadorActionPerformed(evt);
            }
        });

        lbBuscar.setText("Buscar:");

        lbinfo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbinfo.setText("Ingrese la actualizacion de la herramienta.");
        lbinfo.setToolTipText("");

        lbCódigo.setText("Código:");

        lbCódigoRequerido.setForeground(new java.awt.Color(153, 0, 0));
        lbCódigoRequerido.setText("*");

        txtCodigo.setEditable(false);

        lbNombre.setText("Nombre:");

        lbNombreRequerido.setForeground(new java.awt.Color(153, 0, 0));
        lbNombreRequerido.setText("*");

        lbCantidad.setText("Cantidad:");

        lbCantidadRequerida.setForeground(new java.awt.Color(153, 0, 0));
        lbCantidadRequerida.setText("*");

        lbTipo.setText("Tipo:");

        lbTipoRequerido.setForeground(new java.awt.Color(153, 0, 0));
        lbTipoRequerido.setText("*");

        comboxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo", "Celular", "Equipo de computo", "Muebles y enseres", "Tablets", "Vehículos ", " ", " " }));

        txtCantidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        lbEstado.setText("Estado:");

        lbEstadoRequerido.setForeground(new java.awt.Color(153, 0, 0));
        lbEstadoRequerido.setText("*");

        chkActivo.setText("Activo");
        chkActivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkActivoActionPerformed(evt);
            }
        });

        chkInactivo.setText("Inactivo");
        chkInactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkInactivoActionPerformed(evt);
            }
        });

        lbFragilidad.setText("Fragilidad:");

        lbFragilidadRequerido.setForeground(new java.awt.Color(204, 0, 0));
        lbFragilidadRequerido.setText("*");

        comboxFragilidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la fragilidad", "Muy Frágil", "Frágil", "Normal", "Resistente\t", "Muy Resistente" }));

        lbDescripción.setText("Descripción:");

        lbDescripcionRequerida.setForeground(new java.awt.Color(204, 0, 0));
        lbDescripcionRequerida.setText("*");

        javax.swing.GroupLayout panelRegistroActivoLayout = new javax.swing.GroupLayout(panelRegistroActivo);
        panelRegistroActivo.setLayout(panelRegistroActivoLayout);
        panelRegistroActivoLayout.setHorizontalGroup(
            panelRegistroActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroActivoLayout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(lbinfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelRegistroActivoLayout.createSequentialGroup()
                .addGroup(panelRegistroActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistroActivoLayout.createSequentialGroup()
                        .addComponent(lbCódigo)
                        .addGap(15, 15, 15)
                        .addComponent(lbCódigoRequerido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(lbTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTipoRequerido)
                        .addGap(12, 12, 12)
                        .addComponent(comboxTipo, 0, 432, Short.MAX_VALUE))
                    .addGroup(panelRegistroActivoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelRegistroActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(separadorEncabezado)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRegistroActivoLayout.createSequentialGroup()
                                .addGroup(panelRegistroActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNombre)
                                    .addComponent(lbCantidad)
                                    .addGroup(panelRegistroActivoLayout.createSequentialGroup()
                                        .addGroup(panelRegistroActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelRegistroActivoLayout.createSequentialGroup()
                                                .addGap(57, 57, 57)
                                                .addGroup(panelRegistroActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbNombreRequerido, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(lbCantidadRequerida)))
                                            .addComponent(lbDescripción, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(panelRegistroActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNombre)
                                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbDescripcionRequerida))))
                                .addGap(18, 18, 18)
                                .addGroup(panelRegistroActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelRegistroActivoLayout.createSequentialGroup()
                                        .addComponent(lbEstado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbEstadoRequerido)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chkActivo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(chkInactivo)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(panelRegistroActivoLayout.createSequentialGroup()
                                        .addComponent(lbFragilidad)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbFragilidadRequerido, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboxFragilidad, 0, 401, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        panelRegistroActivoLayout.setVerticalGroup(
            panelRegistroActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistroActivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbinfo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRegistroActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelRegistroActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbCódigo)
                        .addComponent(lbCódigoRequerido)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbTipo)
                        .addComponent(lbTipoRequerido))
                    .addComponent(comboxTipo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelRegistroActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(lbNombreRequerido)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEstado)
                    .addComponent(lbEstadoRequerido)
                    .addComponent(chkActivo)
                    .addComponent(chkInactivo))
                .addGap(18, 18, 18)
                .addGroup(panelRegistroActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCantidad)
                    .addComponent(lbCantidadRequerida)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFragilidad)
                    .addComponent(comboxFragilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFragilidadRequerido, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(panelRegistroActivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbDescripción, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbDescripcionRequerida))
                .addGap(75, 75, 75))
        );

        txtareaDescripcion.setColumns(20);
        txtareaDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtareaDescripcion);

        btLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/clean-16.png"))); // NOI18N
        btLimpiar.setText("Limpiar");
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        btActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/Iconos/save-16.png"))); // NOI18N
        btActualizar.setText("Actualizar");
        btActualizar.setEnabled(false);
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(309, 309, 309)
                                .addComponent(btnBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiarBuscador))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(lbBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 271, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btLimpiar)
                        .addGap(13, 13, 13)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(320, 320, 320)
                .addComponent(lbInformacionFiltrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelRegistroActivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbInformacionFiltrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpiarBuscador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelRegistroActivo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btActualizar)
                    .addComponent(btLimpiar))
                .addGap(96, 96, 96))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
        if (this.txtCodigo.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "El código es requerido.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.txtCodigo.requestFocus();
            return;
        }
        if (this.comboxTipo.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un tipo de activo.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.comboxTipo.requestFocus();
            return;
        }
        if (this.txtNombre.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "El nombre es requerido.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.txtNombre.requestFocus();
            return;
        }
        if (!this.chkActivo.isSelected() && !this.chkInactivo.isSelected()) {
            JOptionPane.showMessageDialog(this, "Marque un estado.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if (this.txtCantidad.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "La cantidad es requerida.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.txtCantidad.requestFocus();
            return;
        }
        if (this.comboxFragilidad.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Seleccione la fragilidad del activo.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.comboxFragilidad.requestFocus();
            return;
        }
        if (this.txtareaDescripcion.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "Introduzca la descripcion del activo.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.txtareaDescripcion.requestFocus();
            return;
        }

        this.myGestor = new clsGestor();

        boolean estado;
        if (this.chkActivo.isSelected()) {
            estado = true;
        } else {
            estado = false;
        }
        clsActivo myActivo = new clsActivo(
                this.idActivo,
                this.txtCodigo.getText().trim(),
                this.comboxTipo.getSelectedItem().toString(),
                this.comboxFragilidad.getSelectedItem().toString(),
                this.txtNombre.getText().trim(),
                this.txtareaDescripcion.getText().trim(),
                estado,
                Integer.parseInt(this.txtCantidad.getValue().toString()),
                this.comboxFragilidad.getSelectedItem().toString()
        );
        boolean operacion = myGestor.ActualizarActivo(myActivo);
        if (operacion) {
            JOptionPane.showMessageDialog(this, "Se guardo la información correctamente.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
            this.LimpiarFormulario();
            this.txtCodigo.requestFocus();
        } else {
            JOptionPane.showMessageDialog(this, "No se logro guardar la información correctamente, Intentar nuevamente.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btActualizarActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        this.LimpiarFormulario();
    }//GEN-LAST:event_btLimpiarActionPerformed
    private void LimpiarFormulario() {
        this.txtCodigo.setText("");
        this.txtBuscar.setText("");
        this.comboxTipo.setSelectedIndex(0);
        this.txtNombre.setText("");
        this.chkInactivo.setSelected(false);
        this.chkActivo.setSelected(false);
        this.txtCantidad.setText("");
        this.txtCantidad.setValue(null);
        this.comboxFragilidad.setSelectedIndex(0);
        this.txtareaDescripcion.setText("");
    }
    private void chkInactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkInactivoActionPerformed
        if (this.chkActivo.isSelected()) {
            this.chkActivo.setSelected(false);
        }
    }//GEN-LAST:event_chkInactivoActionPerformed

    private void chkActivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkActivoActionPerformed
        if (this.chkInactivo.isSelected()) {
            this.chkInactivo.setSelected(false);
        }
    }//GEN-LAST:event_chkActivoActionPerformed

    private void btnLimpiarBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarBuscadorActionPerformed
        this.txtBuscar.setText("");
        this.txtBuscar.requestFocus();
    }//GEN-LAST:event_btnLimpiarBuscadorActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        this.txtBuscar.requestFocus();
        this.Buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed
    private void Buscar() {
        String codigo = this.txtBuscar.getText().trim().toLowerCase();

        if (!codigo.isBlank() && !codigo.isEmpty()) {
            clsActivo myEmpleado = this.myGestor.ConsultarActivo(Integer.valueOf(codigo));

            if (myEmpleado != null && myEmpleado.getIdActivo() > 0) {
                this.btActualizar.setEnabled(true);
                this.idActivo = myEmpleado.getIdActivo();
                this.txtCodigo.setText(myEmpleado.getCodigo());
                this.txtNombre.setText(myEmpleado.getNombre());
                this.txtCantidad.setText(myEmpleado.getCantidad() + "");
                this.txtCantidad.setValue(myEmpleado.getCantidad());
                this.comboxTipo.setSelectedItem(myEmpleado.getTipo());
                this.comboxFragilidad.setSelectedItem(myEmpleado.getFragilidad());
                if (myEmpleado.isEstado()) {
                    this.chkActivo.setSelected(true);
                } else {
                    this.chkInactivo.setSelected(true);
                }
                this.txtareaDescripcion.setText(myEmpleado.getDescripcion());
                this.btActualizar.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(this, "No se ha encontrado ningun activo con ese codigo..",
                        "Aviso", JOptionPane.WARNING_MESSAGE);
                this.btActualizar.setEnabled(false);
                this.txtBuscar.setText("");
            }
        }

    }

    private void txtBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.Buscar();
        }
    }//GEN-LAST:event_txtBuscarKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiarBuscador;
    private javax.swing.JCheckBox chkActivo;
    private javax.swing.JCheckBox chkInactivo;
    private javax.swing.JComboBox<String> comboxFragilidad;
    private javax.swing.JComboBox<String> comboxTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBuscar;
    private javax.swing.JLabel lbCantidad;
    private javax.swing.JLabel lbCantidadRequerida;
    private javax.swing.JLabel lbCódigo;
    private javax.swing.JLabel lbCódigoRequerido;
    private javax.swing.JLabel lbDescripcionRequerida;
    private javax.swing.JLabel lbDescripción;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbEstadoRequerido;
    private javax.swing.JLabel lbFragilidad;
    private javax.swing.JLabel lbFragilidadRequerido;
    private javax.swing.JLabel lbInformacionFiltrar;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNombreRequerido;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lbTipoRequerido;
    private javax.swing.JLabel lbinfo;
    private javax.swing.JPanel panelRegistroActivo;
    private javax.swing.JSeparator separadorEncabezado;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JFormattedTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtareaDescripcion;
    // End of variables declaration//GEN-END:variables
}
